
spring:   
  datasource:
    url: jdbc:mysql://mysql:3306/sampledb
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
